### PR TITLE
added household and bill and wishgroup functionality

### PR DESCRIPTION
**Pull request by jooleyaz**
also changed some things to lower camelcase

### CODE REVIEW

**Review by cameronl10 — CHANGES_REQUESTED** [review]
remove allocation.ts, bill.ts, billHandler.ts, allocationHandler.ts

**Comment by jaykbpark** [comment]
good refactor 👍

**Comment by jaykbpark** [comment]
🤣

**Review by cameronl10 — APPROVED** [review]
removed import

**Review by cameronl10 — APPROVED** [review]
lgtm

**Review by cameronl10 — APPROVED** [review]
lgtm

**Review by eriklsy — APPROVED** [review]
lgtm

**Pull request merged**
